public class __M$Data_Time_Gen {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Time.Gen"); }
    };


public static final Object genTime = __init$genTime();
    private static Object __init$genTime() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0$r0) -> { Object Bind1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Apply0_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1$r1).get("Apply0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Apply0_2$r2).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Apply0_2$r2).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Apply0_2$r2).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1$r1).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time.Time))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Component_Gen.genHour)).apply(dictMonadGen_0$r0))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Component_Gen.genMinute)).apply(dictMonadGen_0$r0))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Component_Gen.genSecond)).apply(dictMonadGen_0$r0))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Component_Gen.genMillisecond)).apply(dictMonadGen_0$r0)); }; }
}
