public class __M$Data_Time_Duration {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Time.Duration"); }
    };


public static final Object Seconds = __init$Seconds();
    private static Object __init$Seconds() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object Minutes = __init$Minutes();
    private static Object __init$Minutes() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object Milliseconds = __init$Milliseconds();
    private static Object __init$Milliseconds() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object Hours = __init$Hours();
    private static Object __init$Hours() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object Days = __init$Days();
    private static Object __init$Days() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object toDuration = __init$toDuration();
    private static Object __init$toDuration() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("toDuration"); }; }
public static final Object showSeconds = __init$showSeconds();
    private static Object __init$showSeconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((String) ((((String) ("(Seconds ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0$r0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }
public static final Object showMinutes = __init$showMinutes();
    private static Object __init$showMinutes() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((String) ((((String) ("(Minutes ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0$r0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }
public static final Object showMilliseconds = __init$showMilliseconds();
    private static Object __init$showMilliseconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((String) ((((String) ("(Milliseconds ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0$r0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }
public static final Object showHours = __init$showHours();
    private static Object __init$showHours() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((String) ((((String) ("(Hours ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0$r0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }
public static final Object showDays = __init$showDays();
    private static Object __init$showDays() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((String) ((((String) ("(Days ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0$r0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }
public static final Object semigroupSeconds = __init$semigroupSeconds();
    private static Object __init$semigroupSeconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (((Double) (v_0$r0)) + ((Double) (v1_1$r1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object semigroupMinutes = __init$semigroupMinutes();
    private static Object __init$semigroupMinutes() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (((Double) (v_0$r0)) + ((Double) (v1_1$r1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object semigroupMilliseconds = __init$semigroupMilliseconds();
    private static Object __init$semigroupMilliseconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (((Double) (v_0$r0)) + ((Double) (v1_1$r1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object semigroupHours = __init$semigroupHours();
    private static Object __init$semigroupHours() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (((Double) (v_0$r0)) + ((Double) (v1_1$r1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object semigroupDays = __init$semigroupDays();
    private static Object __init$semigroupDays() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (((Double) (v_0$r0)) + ((Double) (v1_1$r1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object ordSeconds = __init$ordSeconds();
    private static Object __init$ordSeconds() { return __M$Data_Ord.ordNumber; }
public static final Object ordMinutes = __init$ordMinutes();
    private static Object __init$ordMinutes() { return __M$Data_Ord.ordNumber; }
public static final Object ordMilliseconds = __init$ordMilliseconds();
    private static Object __init$ordMilliseconds() { return __M$Data_Ord.ordNumber; }
public static final Object ordHours = __init$ordHours();
    private static Object __init$ordHours() { return __M$Data_Ord.ordNumber; }
public static final Object ordDays = __init$ordDays();
    private static Object __init$ordDays() { return __M$Data_Ord.ordNumber; }
public static final Object newtypeSeconds = __init$newtypeSeconds();
    private static Object __init$newtypeSeconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object newtypeMinutes = __init$newtypeMinutes();
    private static Object __init$newtypeMinutes() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object newtypeMilliseconds = __init$newtypeMilliseconds();
    private static Object __init$newtypeMilliseconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object newtypeHours = __init$newtypeHours();
    private static Object __init$newtypeHours() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object newtypeDays = __init$newtypeDays();
    private static Object __init$newtypeDays() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object monoidSeconds = __init$monoidSeconds();
    private static Object __init$monoidSeconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Time_Duration.semigroupSeconds; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidMinutes = __init$monoidMinutes();
    private static Object __init$monoidMinutes() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Time_Duration.semigroupMinutes; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidMilliseconds = __init$monoidMilliseconds();
    private static Object __init$monoidMilliseconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Time_Duration.semigroupMilliseconds; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidHours = __init$monoidHours();
    private static Object __init$monoidHours() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Time_Duration.semigroupHours; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidDays = __init$monoidDays();
    private static Object __init$monoidDays() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Time_Duration.semigroupDays; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object fromDuration = __init$fromDuration();
    private static Object __init$fromDuration() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("fromDuration"); }; }
public static final Object negateDuration = __init$negateDuration();
    private static Object __init$negateDuration() { return (java.util.function.Function<Object, Object>) (dictDuration_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.toDuration)).apply(dictDuration_0$r0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (__local_var_1$r1) -> { return (-(((Double) (__local_var_1$r1)))); })))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.fromDuration)).apply(dictDuration_0$r0))); }; }
public static final Object eqSeconds = __init$eqSeconds();
    private static Object __init$eqSeconds() { return __M$Data_Eq.eqNumber; }
public static final Object eqMinutes = __init$eqMinutes();
    private static Object __init$eqMinutes() { return __M$Data_Eq.eqNumber; }
public static final Object eqMilliseconds = __init$eqMilliseconds();
    private static Object __init$eqMilliseconds() { return __M$Data_Eq.eqNumber; }
public static final Object eqHours = __init$eqHours();
    private static Object __init$eqHours() { return __M$Data_Eq.eqNumber; }
public static final Object eqDays = __init$eqDays();
    private static Object __init$eqDays() { return __M$Data_Eq.eqNumber; }
public static final Object durationSeconds = __init$durationSeconds();
    private static Object __init$durationSeconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((Double) (v_0$r0)) * ((Double) (1000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r1) -> { return (((Double) (v_0$r1)) / ((Double) (1000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get(); }
public static final Object durationMinutes = __init$durationMinutes();
    private static Object __init$durationMinutes() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((Double) (v_0$r0)) * ((Double) (60000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r1) -> { return (((Double) (v_0$r1)) / ((Double) (60000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get(); }
public static final Object durationMilliseconds = __init$durationMilliseconds();
    private static Object __init$durationMilliseconds() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; final Object __field1 = (java.util.function.Function<Object, Object>) (x_0$r1) -> { return x_0$r1; }; return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get(); }
public static final Object durationHours = __init$durationHours();
    private static Object __init$durationHours() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((Double) (v_0$r0)) * ((Double) (3600000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r1) -> { return (((Double) (v_0$r1)) / ((Double) (3600000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get(); }
public static final Object durationDays = __init$durationDays();
    private static Object __init$durationDays() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((Double) (v_0$r0)) * ((Double) (86400000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0$r1) -> { return (((Double) (v_0$r1)) / ((Double) (86400000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get(); }
public static final Object convertDuration = __init$convertDuration();
    private static Object __init$convertDuration() { return (java.util.function.Function<Object, Object>) (dictDuration_0$r0) -> { Object fromDuration1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.fromDuration)).apply(dictDuration_0$r0); return (java.util.function.Function<Object, Object>) (dictDuration1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.toDuration)).apply(dictDuration1_2$r2)))).apply(fromDuration1_1$r1); }; }; }
}
