public class __M$Data_Time_Duration {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Time.Duration"); }
    };


public static final Object Seconds = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object Minutes = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object Milliseconds = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object Hours = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object Days = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object toDuration = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("toDuration"); };
public static final Object showSeconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Seconds ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showMinutes = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Minutes ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Milliseconds ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showHours = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Hours ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showDays = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Days ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showNumberImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object semigroupSeconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (((Double) (v_0_i0)) + ((Double) (v1_1_i1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object semigroupMinutes = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (((Double) (v_0_i0)) + ((Double) (v1_1_i1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object semigroupMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (((Double) (v_0_i0)) + ((Double) (v1_1_i1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object semigroupHours = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (((Double) (v_0_i0)) + ((Double) (v1_1_i1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object semigroupDays = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (((Double) (v_0_i0)) + ((Double) (v1_1_i1))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object ordSeconds = __M$Data_Ord.ordNumber;
public static final Object ordMinutes = __M$Data_Ord.ordNumber;
public static final Object ordMilliseconds = __M$Data_Ord.ordNumber;
public static final Object ordHours = __M$Data_Ord.ordNumber;
public static final Object ordDays = __M$Data_Ord.ordNumber;
public static final Object newtypeSeconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeMinutes = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeHours = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeDays = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidSeconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Time_Duration.semigroupSeconds; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object monoidMinutes = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Time_Duration.semigroupMinutes; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object monoidMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Time_Duration.semigroupMilliseconds; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object monoidHours = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Time_Duration.semigroupHours; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object monoidDays = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0.0; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Time_Duration.semigroupDays; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object fromDuration = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("fromDuration"); };
public static final Object negateDuration = (java.util.function.Function<Object, Object>) (dictDuration_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.toDuration)).apply(dictDuration_0_i0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (__local_var_1_i1) -> { return (-(((Double) (__local_var_1_i1)))); })))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.fromDuration)).apply(dictDuration_0_i0))); };
public static final Object eqSeconds = __M$Data_Eq.eqNumber;
public static final Object eqMinutes = __M$Data_Eq.eqNumber;
public static final Object eqMilliseconds = __M$Data_Eq.eqNumber;
public static final Object eqHours = __M$Data_Eq.eqNumber;
public static final Object eqDays = __M$Data_Eq.eqNumber;
public static final Object durationSeconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((Double) (v_0_i0)) * ((Double) (1000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i1) -> { return (((Double) (v_0_i1)) / ((Double) (1000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get();
public static final Object durationMinutes = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((Double) (v_0_i0)) * ((Double) (60000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i1) -> { return (((Double) (v_0_i1)) / ((Double) (60000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get();
public static final Object durationMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); final Object __field1 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get();
public static final Object durationHours = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((Double) (v_0_i0)) * ((Double) (3600000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i1) -> { return (((Double) (v_0_i1)) / ((Double) (3600000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get();
public static final Object durationDays = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((Double) (v_0_i0)) * ((Double) (86400000.0))); }); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply((java.util.function.Function<Object, Object>) (v_0_i1) -> { return (((Double) (v_0_i1)) / ((Double) (86400000.0))); }); return new __Record$66_72_6f_6d_44_75_72_61_74_69_6f_6e_O$74_6f_44_75_72_61_74_69_6f_6e_O(new String[]{"fromDuration", "toDuration"}, __field0, __field1); } }).get();
public static final Object convertDuration = (java.util.function.Function<Object, Object>) (dictDuration_0_i0) -> { Object fromDuration1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.fromDuration)).apply(dictDuration_0_i0); return (java.util.function.Function<Object, Object>) (dictDuration1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Time_Duration.toDuration)).apply(dictDuration1_2_i2)))).apply(fromDuration1_1_i1); }; };
}
