public class __M$Data_Set_NonEmpty {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Set.NonEmpty"); }
    };


public static final Object unionSet = __init$unionSet();
    private static Object __init$unionSet() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.append)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Set.semigroupSet)).apply(dictOrd_0_i0)); }; }
public static final Object toUnfoldable1 = __init$toUnfoldable1();
    private static Object __init$toUnfoldable1() { return (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> { Object stepNext_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.stepWith)).apply(__M$Data_Map_Internal.iterMapL))).apply((java.util.function.Function<Object, Object>) (k_1_i2) -> (java.util.function.Function<Object, Object>) (__local_var_2_i3) -> (java.util.function.Function<Object, Object>) (__local_var_3_i4) -> { return new __M$Data_Maybe.Just(new __M$Data_Tuple.Tuple(k_1_i2, __local_var_3_i4)); }))).apply((java.util.function.Function<Object, Object>) (v_1_i5) -> { return __M$Data_Maybe.__singleton$Nothing.value; }); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (v_2_i6) -> { return new __M$Data_Tuple.Tuple(((__M$Data_Tuple.Tuple) (Object)(v_2_i6)).value0, ((java.util.function.Function<Object, Object>) (stepNext_1_i1)).apply(((__M$Data_Tuple.Tuple) (Object)(v_2_i6)).value1)); })))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.stepWith)).apply(__M$Data_Map_Internal.iterMapL))).apply((java.util.function.Function<Object, Object>) (k_2_i7) -> (java.util.function.Function<Object, Object>) (__local_var_3_i8) -> (java.util.function.Function<Object, Object>) (__local_var_4_i9) -> { return new __M$Data_Tuple.Tuple(k_2_i7, __local_var_4_i9); }))).apply((java.util.function.Function<Object, Object>) (v_2_i10) -> { return ((java.util.function.Function<Object, Object>) (__M$Partial._crashWith)).apply("toUnfoldable1: impossible"); })))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Map_Internal.toMapIter))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Set.toMap))).apply(((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))))); }; }
public static final Object toUnfoldable = __init$toUnfoldable();
    private static Object __init$toUnfoldable() { return (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.toUnfoldable)).apply(dictUnfoldable_0_i0); }; }
public static final Object toSet = __init$toSet();
    private static Object __init$toSet() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return v_0_i0; }; }
public static final Object subset = __init$subset();
    private static Object __init$subset() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.subset)).apply(dictOrd_0_i0); }; }
public static final Object size = __init$size();
    private static Object __init$size() { return __M$Data_Set.size; }
public static final Object singleton = __init$singleton();
    private static Object __init$singleton() { return __M$Data_Set.singleton; }
public static final Object showNonEmptySet = __init$showNonEmptySet();
    private static Object __init$showNonEmptySet() { return (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { Object showNonEmptyArray_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty_Internal.showNonEmptyArray)).apply(dictShow_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (s_2_i2) -> { return (((String) ((((String) ("(fromFoldable1 ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) showNonEmptyArray_1_i1).get("show"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Set_NonEmpty.toUnfoldable1)).apply(__M$Data_Unfoldable1.unfoldable1Array))).apply(s_2_i2))))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object semigroupNonEmptySet = __init$semigroupNonEmptySet();
    private static Object __init$semigroupNonEmptySet() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.semigroupSet)).apply(dictOrd_0_i0); }; }
public static final Object properSubset = __init$properSubset();
    private static Object __init$properSubset() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.properSubset)).apply(dictOrd_0_i0); }; }
public static final Object ordNonEmptySet = __init$ordNonEmptySet();
    private static Object __init$ordNonEmptySet() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.ordSet)).apply(dictOrd_0_i0); }; }
public static final Object ord1NonEmptySet = __init$ord1NonEmptySet();
    private static Object __init$ord1NonEmptySet() { return __M$Data_Set.ord1Set; }
public static final Object min = __init$min();
    private static Object __init$min() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.findMin)).apply(v_0_i0); return ( ((Boolean) ((((Object) (__local_var_1_i1)) instanceof __M$Data_Maybe.Just))) ? ((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_1_i1)).value0).get("key") : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }; }
public static final Object member = __init$member();
    private static Object __init$member() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.member)).apply(dictOrd_0_i0); }; }
public static final Object max = __init$max();
    private static Object __init$max() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.findMax)).apply(v_0_i0); return ( ((Boolean) ((((Object) (__local_var_1_i1)) instanceof __M$Data_Maybe.Just))) ? ((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_1_i1)).value0).get("key") : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }; }
public static final Object mapMaybe = __init$mapMaybe();
    private static Object __init$mapMaybe() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.mapMaybe)).apply(dictOrd_0_i0); }; }
public static final Object map = __init$map();
    private static Object __init$map() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.map)).apply(dictOrd_0_i0); }; }
public static final Object insert = __init$insert();
    private static Object __init$insert() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.insert)).apply(dictOrd_0_i0); }; }
public static final Object fromSet = __init$fromSet();
    private static Object __init$fromSet() { return (java.util.function.Function<Object, Object>) (s_0_i0) -> { return ( ((Boolean) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.isEmpty)).apply(s_0_i0))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(s_0_i0)); }; }
public static final Object intersection = __init$intersection();
    private static Object __init$intersection() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.intersection)).apply(dictOrd_0_i0))).apply(v_1_i1))).apply(v1_2_i2); return ( ((Boolean) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.isEmpty)).apply(__local_var_3_i3))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__local_var_3_i3)); }; }; }; }
public static final Object fromFoldable1 = __init$fromFoldable1();
    private static Object __init$fromFoldable1() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictOrd_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Set_NonEmpty.semigroupNonEmptySet)).apply(dictOrd_1_i1)))).apply(__M$Data_Set_NonEmpty.singleton); }; }; }
public static final Object fromFoldable = __init$fromFoldable();
    private static Object __init$fromFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictOrd_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Set_NonEmpty.fromSet))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Set.fromFoldable)).apply(dictFoldable_0_i0))).apply(dictOrd_1_i1)); }; }; }
public static final Object foldableNonEmptySet = __init$foldableNonEmptySet();
    private static Object __init$foldableNonEmptySet() { return __M$Data_Set.foldableSet; }
public static final Object foldable1NonEmptySet = __init$foldable1NonEmptySet();
    private static Object __init$foldable1NonEmptySet() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Types.foldable1NonEmptyList).get("foldMap1"))).apply(dictSemigroup_0_i0))).apply(f_1_i1)))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Set_NonEmpty.toUnfoldable1)).apply(__M$Data_List_Types.unfoldable1NonEmptyList)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (f_0_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Types.foldable1NonEmptyList).get("foldr1"))).apply(f_0_i2)))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Set_NonEmpty.toUnfoldable1)).apply(__M$Data_List_Types.unfoldable1NonEmptyList)); }; final Object __field2 = (java.util.function.Function<Object, Object>) (f_0_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Types.foldable1NonEmptyList).get("foldl1"))).apply(f_0_i3)))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Set_NonEmpty.toUnfoldable1)).apply(__M$Data_List_Types.unfoldable1NonEmptyList)); }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i4) -> { return __M$Data_Set.foldableSet; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldr1", "foldl1", "Foldable0"}, __field3, __field0, __field2, __field1); } }).get(); }
public static final Object filter = __init$filter();
    private static Object __init$filter() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.filter)).apply(dictOrd_0_i0); }; }
public static final Object eqNonEmptySet = __init$eqNonEmptySet();
    private static Object __init$eqNonEmptySet() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.eqSet)).apply(dictEq_0_i0); }; }
public static final Object eq1NonEmptySet = __init$eq1NonEmptySet();
    private static Object __init$eq1NonEmptySet() { return __M$Data_Set.eq1Set; }
public static final Object difference = __init$difference();
    private static Object __init$difference() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.difference)).apply(dictOrd_0_i0))).apply(v_1_i1))).apply(v1_2_i2); return ( ((Boolean) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.isEmpty)).apply(__local_var_3_i3))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__local_var_3_i3)); }; }; }; }
public static final Object delete = __init$delete();
    private static Object __init$delete() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (a_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.delete)).apply(dictOrd_0_i0))).apply(a_1_i1))).apply(v_2_i2); return ( ((Boolean) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.isEmpty)).apply(__local_var_3_i3))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__local_var_3_i3)); }; }; }; }
public static final Object cons = __init$cons();
    private static Object __init$cons() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Set.insert)).apply(dictOrd_0_i0); }; }
}
