public class __M$Data_Date_Component_Gen {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Date.Component.Gen"); }
    };


public static final Object genYear = (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> { return ( ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Just))) ? ((__M$Data_Maybe.Just) (Object)(v_1_i1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Date_Component.boundedEnumYear))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseInt"))).apply(1900))).apply(2100)); };
public static final Object genWeekday = (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Enum_Gen.genBoundedEnum)).apply(dictMonadGen_0_i0))).apply(__M$Data_Date_Component.boundedEnumWeekday); };
public static final Object genMonth = (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Enum_Gen.genBoundedEnum)).apply(dictMonadGen_0_i0))).apply(__M$Data_Date_Component.boundedEnumMonth); };
public static final Object genDay = (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Enum_Gen.genBoundedEnum)).apply(dictMonadGen_0_i0))).apply(__M$Data_Date_Component.boundedEnumDay); };
}
