public class __M$Data_Time_Component {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Time.Component"); }
    };


public static final Object showSecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Second ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showIntImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showMinute = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Minute ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showIntImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Millisecond ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showIntImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showHour = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((String) ((((String) ("(Hour ")) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_Show.showIntImpl)).apply(v_0_i0)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object ordSecond = __M$Data_Ord.ordInt;
public static final Object ordMinute = __M$Data_Ord.ordInt;
public static final Object ordMillisecond = __M$Data_Ord.ordInt;
public static final Object ordHour = __M$Data_Ord.ordInt;
public static final Object eqSecond = __M$Data_Eq.eqInt;
public static final Object eqMinute = __M$Data_Eq.eqInt;
public static final Object eqMillisecond = __M$Data_Eq.eqInt;
public static final Object eqHour = __M$Data_Eq.eqInt;
public static final Object boundedSecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0; final Object __field1 = 59; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_I$74_6f_70_I(new String[]{"bottom", "top", "Ord0"}, __field2, ((Integer) (__field0)).intValue(), ((Integer) (__field1)).intValue()); } }).get();
public static final Object boundedMinute = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0; final Object __field1 = 59; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_I$74_6f_70_I(new String[]{"bottom", "top", "Ord0"}, __field2, ((Integer) (__field0)).intValue(), ((Integer) (__field1)).intValue()); } }).get();
public static final Object boundedMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0; final Object __field1 = 999; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_I$74_6f_70_I(new String[]{"bottom", "top", "Ord0"}, __field2, ((Integer) (__field0)).intValue(), ((Integer) (__field1)).intValue()); } }).get();
public static final Object boundedHour = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 0; final Object __field1 = 23; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_I$74_6f_70_I(new String[]{"bottom", "top", "Ord0"}, __field2, ((Integer) (__field0)).intValue(), ((Integer) (__field1)).intValue()); } }).get();
private static Object __lazy_value_boundedEnumSecond;
private static int __lazy_state_boundedEnumSecond;
private static Object __lazy_get_boundedEnumSecond() { if (__lazy_state_boundedEnumSecond == 2) return __lazy_value_boundedEnumSecond; if (__lazy_state_boundedEnumSecond == 1) throw new IllegalStateException("Recursive initialization of boundedEnumSecond"); __lazy_state_boundedEnumSecond = 1; __lazy_value_boundedEnumSecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 60; final Object __field1 = (java.util.function.Function<Object, Object>) (n_0_i0) -> { return ( ((Boolean) ((((Boolean) ((((int) (n_0_i0)) >= ((int) (0))))) && ((Boolean) ((((int) (n_0_i0)) <= ((int) (59)))))))) ? new __M$Data_Maybe.Just(n_0_i0) : __M$Data_Maybe.__singleton$Nothing.value); }; final Object __field2 = (__IntFn) (v_0_i1) -> ((int) (v_0_i1)); final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Time_Component.boundedSecond; }; final Object __field4 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Time_Component.__lazy_get_enumSecond(); }; return new __Record$42_6f_75_6e_64_65_64_30_O$45_6e_75_6d_31_O$63_61_72_64_69_6e_61_6c_69_74_79_O$66_72_6f_6d_45_6e_75_6d_O$74_6f_45_6e_75_6d_O(new String[]{"cardinality", "toEnum", "fromEnum", "Bounded0", "Enum1"}, __field3, __field4, __field0, __field2, __field1); } }).get(); __lazy_state_boundedEnumSecond = 2; return __lazy_value_boundedEnumSecond; }
public static final Object boundedEnumSecond = __lazy_get_boundedEnumSecond();
private static Object __lazy_value_enumSecond;
private static int __lazy_state_enumSecond;
private static Object __lazy_get_enumSecond() { if (__lazy_state_enumSecond == 2) return __lazy_value_enumSecond; if (__lazy_state_enumSecond == 1) throw new IllegalStateException("Recursive initialization of enumSecond"); __lazy_state_enumSecond = 1; __lazy_value_enumSecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumSecond())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i0) -> ((int) ((((int) (v_0_i0)) + ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumSecond()))); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumSecond())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i1) -> ((int) ((((int) (v_0_i1)) - ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumSecond()))); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$70_72_65_64_O$73_75_63_63_O(new String[]{"succ", "pred", "Ord0"}, __field2, __field1, __field0); } }).get(); __lazy_state_enumSecond = 2; return __lazy_value_enumSecond; }
public static final Object enumSecond = __lazy_get_enumSecond();
private static Object __lazy_value_boundedEnumMinute;
private static int __lazy_state_boundedEnumMinute;
private static Object __lazy_get_boundedEnumMinute() { if (__lazy_state_boundedEnumMinute == 2) return __lazy_value_boundedEnumMinute; if (__lazy_state_boundedEnumMinute == 1) throw new IllegalStateException("Recursive initialization of boundedEnumMinute"); __lazy_state_boundedEnumMinute = 1; __lazy_value_boundedEnumMinute = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 60; final Object __field1 = (java.util.function.Function<Object, Object>) (n_0_i0) -> { return ( ((Boolean) ((((Boolean) ((((int) (n_0_i0)) >= ((int) (0))))) && ((Boolean) ((((int) (n_0_i0)) <= ((int) (59)))))))) ? new __M$Data_Maybe.Just(n_0_i0) : __M$Data_Maybe.__singleton$Nothing.value); }; final Object __field2 = (__IntFn) (v_0_i1) -> ((int) (v_0_i1)); final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Time_Component.boundedMinute; }; final Object __field4 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Time_Component.__lazy_get_enumMinute(); }; return new __Record$42_6f_75_6e_64_65_64_30_O$45_6e_75_6d_31_O$63_61_72_64_69_6e_61_6c_69_74_79_O$66_72_6f_6d_45_6e_75_6d_O$74_6f_45_6e_75_6d_O(new String[]{"cardinality", "toEnum", "fromEnum", "Bounded0", "Enum1"}, __field3, __field4, __field0, __field2, __field1); } }).get(); __lazy_state_boundedEnumMinute = 2; return __lazy_value_boundedEnumMinute; }
public static final Object boundedEnumMinute = __lazy_get_boundedEnumMinute();
private static Object __lazy_value_enumMinute;
private static int __lazy_state_enumMinute;
private static Object __lazy_get_enumMinute() { if (__lazy_state_enumMinute == 2) return __lazy_value_enumMinute; if (__lazy_state_enumMinute == 1) throw new IllegalStateException("Recursive initialization of enumMinute"); __lazy_state_enumMinute = 1; __lazy_value_enumMinute = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMinute())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i0) -> ((int) ((((int) (v_0_i0)) + ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMinute()))); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMinute())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i1) -> ((int) ((((int) (v_0_i1)) - ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMinute()))); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$70_72_65_64_O$73_75_63_63_O(new String[]{"succ", "pred", "Ord0"}, __field2, __field1, __field0); } }).get(); __lazy_state_enumMinute = 2; return __lazy_value_enumMinute; }
public static final Object enumMinute = __lazy_get_enumMinute();
private static Object __lazy_value_boundedEnumMillisecond;
private static int __lazy_state_boundedEnumMillisecond;
private static Object __lazy_get_boundedEnumMillisecond() { if (__lazy_state_boundedEnumMillisecond == 2) return __lazy_value_boundedEnumMillisecond; if (__lazy_state_boundedEnumMillisecond == 1) throw new IllegalStateException("Recursive initialization of boundedEnumMillisecond"); __lazy_state_boundedEnumMillisecond = 1; __lazy_value_boundedEnumMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 1000; final Object __field1 = (java.util.function.Function<Object, Object>) (n_0_i0) -> { return ( ((Boolean) ((((Boolean) ((((int) (n_0_i0)) >= ((int) (0))))) && ((Boolean) ((((int) (n_0_i0)) <= ((int) (999)))))))) ? new __M$Data_Maybe.Just(n_0_i0) : __M$Data_Maybe.__singleton$Nothing.value); }; final Object __field2 = (__IntFn) (v_0_i1) -> ((int) (v_0_i1)); final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Time_Component.boundedMillisecond; }; final Object __field4 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Time_Component.__lazy_get_enumMillisecond(); }; return new __Record$42_6f_75_6e_64_65_64_30_O$45_6e_75_6d_31_O$63_61_72_64_69_6e_61_6c_69_74_79_O$66_72_6f_6d_45_6e_75_6d_O$74_6f_45_6e_75_6d_O(new String[]{"cardinality", "toEnum", "fromEnum", "Bounded0", "Enum1"}, __field3, __field4, __field0, __field2, __field1); } }).get(); __lazy_state_boundedEnumMillisecond = 2; return __lazy_value_boundedEnumMillisecond; }
public static final Object boundedEnumMillisecond = __lazy_get_boundedEnumMillisecond();
private static Object __lazy_value_enumMillisecond;
private static int __lazy_state_enumMillisecond;
private static Object __lazy_get_enumMillisecond() { if (__lazy_state_enumMillisecond == 2) return __lazy_value_enumMillisecond; if (__lazy_state_enumMillisecond == 1) throw new IllegalStateException("Recursive initialization of enumMillisecond"); __lazy_state_enumMillisecond = 1; __lazy_value_enumMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMillisecond())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i0) -> ((int) ((((int) (v_0_i0)) + ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMillisecond()))); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMillisecond())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i1) -> ((int) ((((int) (v_0_i1)) - ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumMillisecond()))); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$70_72_65_64_O$73_75_63_63_O(new String[]{"succ", "pred", "Ord0"}, __field2, __field1, __field0); } }).get(); __lazy_state_enumMillisecond = 2; return __lazy_value_enumMillisecond; }
public static final Object enumMillisecond = __lazy_get_enumMillisecond();
private static Object __lazy_value_boundedEnumHour;
private static int __lazy_state_boundedEnumHour;
private static Object __lazy_get_boundedEnumHour() { if (__lazy_state_boundedEnumHour == 2) return __lazy_value_boundedEnumHour; if (__lazy_state_boundedEnumHour == 1) throw new IllegalStateException("Recursive initialization of boundedEnumHour"); __lazy_state_boundedEnumHour = 1; __lazy_value_boundedEnumHour = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = 24; final Object __field1 = (java.util.function.Function<Object, Object>) (n_0_i0) -> { return ( ((Boolean) ((((Boolean) ((((int) (n_0_i0)) >= ((int) (0))))) && ((Boolean) ((((int) (n_0_i0)) <= ((int) (23)))))))) ? new __M$Data_Maybe.Just(n_0_i0) : __M$Data_Maybe.__singleton$Nothing.value); }; final Object __field2 = (__IntFn) (v_0_i1) -> ((int) (v_0_i1)); final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Time_Component.boundedHour; }; final Object __field4 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Time_Component.__lazy_get_enumHour(); }; return new __Record$42_6f_75_6e_64_65_64_30_O$45_6e_75_6d_31_O$63_61_72_64_69_6e_61_6c_69_74_79_O$66_72_6f_6d_45_6e_75_6d_O$74_6f_45_6e_75_6d_O(new String[]{"cardinality", "toEnum", "fromEnum", "Bounded0", "Enum1"}, __field3, __field4, __field0, __field2, __field1); } }).get(); __lazy_state_boundedEnumHour = 2; return __lazy_value_boundedEnumHour; }
public static final Object boundedEnumHour = __lazy_get_boundedEnumHour();
private static Object __lazy_value_enumHour;
private static int __lazy_state_enumHour;
private static Object __lazy_get_enumHour() { if (__lazy_state_enumHour == 2) return __lazy_value_enumHour; if (__lazy_state_enumHour == 1) throw new IllegalStateException("Recursive initialization of enumHour"); __lazy_state_enumHour = 1; __lazy_value_enumHour = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumHour())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i0) -> ((int) ((((int) (v_0_i0)) + ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumHour()))); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.toEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumHour())))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((__IntFn) (v_0_i1) -> ((int) ((((int) (v_0_i1)) - ((int) (1)))))))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Enum.fromEnum)).apply(__M$Data_Time_Component.__lazy_get_boundedEnumHour()))); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Ord.ordInt; }; return new __Record$4f_72_64_30_O$70_72_65_64_O$73_75_63_63_O(new String[]{"succ", "pred", "Ord0"}, __field2, __field1, __field0); } }).get(); __lazy_state_enumHour = 2; return __lazy_value_enumHour; }
public static final Object enumHour = __lazy_get_enumHour();
}
