public class __M$Data_Time_Duration_Gen {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Time.Duration.Gen"); }
    };


public static final Object genSeconds = __init$genSeconds();
    private static Object __init$genSeconds() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time_Duration.Seconds))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseFloat"))).apply(0.0))).apply(600.0)); }; }
public static final Object genMinutes = __init$genMinutes();
    private static Object __init$genMinutes() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time_Duration.Minutes))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseFloat"))).apply(0.0))).apply(600.0)); }; }
public static final Object genMilliseconds = __init$genMilliseconds();
    private static Object __init$genMilliseconds() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time_Duration.Milliseconds))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseFloat"))).apply(0.0))).apply(600000.0)); }; }
public static final Object genHours = __init$genHours();
    private static Object __init$genHours() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time_Duration.Hours))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseFloat"))).apply(0.0))).apply(240.0)); }; }
public static final Object genDays = __init$genDays();
    private static Object __init$genDays() { return (java.util.function.Function<Object, Object>) (dictMonadGen_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(__M$Data_Time_Duration.Days))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadGen_0_i0).get("chooseFloat"))).apply(0.0))).apply(42.0)); }; }
}
