public class __M$Data_Map {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Map"); }
    };


public static final Object SemigroupMap = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object traversableWithIndexSemigroupMap = __M$Data_Map_Internal.traversableWithIndexMap;
public static final Object traversableSemigroupMap = __M$Data_Map_Internal.traversableMap;
public static final Object showSemigroupMap = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictShow1_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.showMap)).apply(dictShow_0_i0))).apply(dictShow1_1_i1); }; };
public static final Object semigroupSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> { return __M$Data_Map.__direct$4(dictOrd_0_i0, dictSemigroup_1_i1); }; };
private static Object __direct$4(Object dictOrd_0_i0, Object dictSemigroup_1_i1) { Object append_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.append)).apply(dictSemigroup_1_i1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_3_i3) -> { return (java.util.function.Function<Object, Object>) (v1_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.unsafeUnionWith)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(dictOrd_0_i0)))).apply(append_2_i2))).apply(v_3_i3))).apply(v1_4_i4); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object plusSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.plusMap)).apply(dictOrd_0_i0); };
public static final Object ordSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { Object ordMap_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.ordMap)).apply(dictOrd_0_i0); return (java.util.function.Function<Object, Object>) (dictOrd1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (ordMap_1_i1)).apply(dictOrd1_2_i2); }; };
public static final Object ord1SemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.ord1Map)).apply(dictOrd_0_i0); };
public static final Object newtypeSemigroupMap = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> { Object semigroupSemigroupMap2_2_i2 = ( ((Boolean) ((__M$Data_Map.semigroupSemigroupMap == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map.semigroupSemigroupMap)).apply(dictOrd_0_i0))).apply(dictSemigroup_1_i1) : __M$Data_Map.__direct$4(dictOrd_0_i0, dictSemigroup_1_i1)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Map_Internal.empty; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3_i3) -> { return semigroupSemigroupMap2_2_i2; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; };
public static final Object keys = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Set.fromMap))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Functor.$void)).apply(__M$Data_Map_Internal.functorMap));
public static final Object functorWithIndexSemigroupMap = __M$Data_Map_Internal.functorWithIndexMap;
public static final Object functorSemigroupMap = __M$Data_Map_Internal.functorMap;
public static final Object foldableWithIndexSemigroupMap = __M$Data_Map_Internal.foldableWithIndexMap;
public static final Object foldableSemigroupMap = __M$Data_Map_Internal.foldableMap;
public static final Object eqSemigroupMap = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictEq1_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.eqMap)).apply(dictEq_0_i0))).apply(dictEq1_1_i1); }; };
public static final Object eq1SemigroupMap = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.eq1Map)).apply(dictEq_0_i0); };
public static final Object bindSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.bindMap)).apply(dictOrd_0_i0); };
public static final Object applySemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.applyMap)).apply(dictOrd_0_i0); };
public static final Object altSemigroupMap = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Map_Internal.altMap)).apply(dictOrd_0_i0); };
}
